highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://MaxWhitney.github.io/
author: Max Whitney

# edit this section with your information
# MaxWhitney.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae
title: Max Whitney's Resume
name: Max Whitney
email: mwx@protonmail.com
# email_full is the mailto: format
email_full: mailto:mwx@protonmail.com
# finally getting around to trying to do that full on blog & vitae
website: maxwhitney.github.io/sustain
website_full: https://maxwhitney.github.io/sustain
github: MaxWhitney
twitter: maxwhitney
#tel: +1 000 0000000
#tel_full: tel:+10000000000
google_maps: 'https://www.google.com/maps/place/New+York+City'
address:
  city: New York City
  state: New York
  country: United States
google_analytics: UA-112887571-1

# needed for travis-ci build
exclude: [vendor]
